# Generated by Django 5.0.2 on 2024-03-31 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0007_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_perdida', models.DateField(auto_now_add=True)),
                ('causa', models.TextField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto')),
            ],
        ),
    ]
