# Generated by Django 5.0.2 on 2024-03-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrs',
            name='tipo',
        ),
    ]
