# Generated by Django 5.0.2 on 2024-03-31 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('devoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
        ),
    ]
