# Generated by Django 5.0.2 on 2024-03-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_precio_unitario_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='porcentaje_ganancia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
