# Generated by Django 5.0.2 on 2024-03-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_porcentaje_ganancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio_unitario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
