# Generated by Django 5.0.2 on 2024-03-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_precio_unitario_alter_compra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
